---
name: Testing farm tests

on:
  issue_comment:
    types:
      - created

jobs:
  testingfarm:
    name: "Run in testing farm"
    runs-on: ubuntu-latest
    environment: testing-farm
    if: |
      github.event.issue.pull_request
      && contains(github.event.comment.body, '[test]')
      && contains(fromJson('["OWNER", "MEMBER"]'), github.event.comment.author_association)
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: "refs/pull/${{ github.event.issue.number }}/head"
        submodules: true

    - name: Run the tests
      uses: sclorg/testing-farm-as-github-action@main
      with:
        compose: Fedora-39
        api_key: ${{ secrets.TF_API_KEY }}
        git_url: "https://github.com/${{ github.repository }}"
        git_ref: "refs/pull/${{ github.event.issue.number }}/head"
        path: "ansible"
        tmt_plan_regex: "testing-farm"
        pull_request_status_name: "Testing farm"
        update_pull_request_status: true
        tf_scope: private
        variables: "PR_NUMBER=${{ github.event.issue.number }}"
